apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
  selector:
    matchLabels:
      run: nginx-dep
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-dep
    spec:
      containers:
      - name: nginx-dep
        image: nginx:1.18.0
