apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
spec:
  template:
    spec:
      containers:
      - name: nginx-dep
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
